// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js dùng .env.local; Prisma CLI mặc định chỉ đọc .env nên nạp thủ công.
config({ path: ".env.local" });
config(); // fallback .env (không override giá trị đã có)

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations dùng kết nối trực tiếp (DIRECT_URL) để tránh pgbouncer;
    // fallback về DATABASE_URL khi chạy local không tách connection pooling.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
